version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: hans
      MONGO_INITDB_ROOT_PASSWORD: hans
    ports:
      - 27017:27017
    volumes:
      - ./.docker/mongoVolume:/data/db
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.docker/nginx:/etc/nginx/conf.d
      - ./backend/public:/delivery/public
    network_mode: host

volumes:
  mongodb_data_container:
